[package]
name = "beatsaber"
version = "0.1.0"
authors = ["Jezza <jezzadabomb@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.20"
err-derive = "0.1.5"

[dependencies.serde]
version = "*"
features = ["derive"]
